name: hexlet-check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hexlet project check
        uses: hexlet/project-action@release

        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install, build
        run: |
          make install
        env:
          CI: true

      - name: run linter
        - run: make lint
