name: hexlet-check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hexlet project check
        uses: hexlet/project-action@release
        with:
          node-version: '14.x'
        - run: make install
        - run: make lint
        - run: make test
