name: Node CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hexlet project check
        uses: hexlet/project-action@release
      - name: Node CI check, setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Npm install, build
        run: |
          make install
        env:
          CI: true
      - name: Run linter
        run: |
          make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
